.gitignore
CHANGELOG.md
README.md
dist/almanac.js
dist/engine.js
docs/almanac.md
docs/engine.md
examples/basic.js
examples/fact-dependecy.js
examples/support/account-api-client.js
package.json
src/almanac.js
src/engine.js
test/almanac.test.js

* Completed the 'fact-dependecy' advanced example
* Updated addFact and addRule engine methods to return 'this' for easy chaining

Docs+tweaks

---

CHANGELOG.md
README.md
dist/almanac.js
dist/engine-facts.js
dist/engine.js
dist/fact.js
docs/engine.md
package.json
src/almanac.js
src/engine-facts.js
src/engine.js
src/fact.js
test/almanac.test.js
test/engine-facts.test.js
test/engine-run.test.js

- engine.run() will now return all triggered events

Success events

---

docs/engine.md
examples/custom-operators.js
src/condition.js
src/engine-default-operators.js
src/engine.js
src/json-rules-engine.js
src/operator.js
src/rule.js
test/condition.test.js
test/engine-operator.test.js
test/engine.test.js
test/operator.test.js

@ctaity @slmmm - implementation of what we were discussing earlier this week.  API turned out to be essentially what we'd discussed - details described in documentation below.   Let me know if you have any feedback.

Custom operators

---

dist/engine-default-operators.js
src/engine-default-operators.js

for backwards compatibility with older versions of ecmascript

convert array operators to use indexOf instead of includes

---

dist/almanac.js
dist/condition.js
dist/engine-facts.js
dist/engine.js
dist/generator-runtime.js
dist/rule.js
package.json

Update object-hash to 1.1.5 this resolves an issue with memory leaks and increases performance

update object-hash dependency

---

README.md

- add npm downloads / month
`json-rules-engine` is rocking!

add npm downloads / month

---

package-lock.json
package.json
src/debug.js

Fix browser debug

---

CHANGELOG.md
package-lock.json
package.json
test/engine-fact.test.js

Fixes #175 by upgrading to the latest jsonpath-plus, which includes consistent scalar results

Json path fix scalars

---

package.json
types/index.d.ts
types/index.test-d.ts

update types for removeRule / updateRule

---

package.json

Upgrades to HashIt and JSON Path Plus. These libraries are major
versions out-of date.

Upgrades to Dependencies

---

.github/workflows/deploy.yml

Add Linting to the CI and move deployment out of the on pull request bit so it doesn't trigger on pull requests.

Add Linting to CI, split deployment

---

package.json

New Features are the not comparison and the ability to add names to conditions.

Bump Package Version to 6.2.0

---

package.json

Version 6.3 includes support for sharable conditions that allow for composition of rules.

Update Version to 6.3.0

---

package.json

Update the minor version to 6.6.0 to release the Operator Decorator feature and other fixes.

Version 6.6.0

---

.github/workflows/deploy.yml
.github/workflows/node.js.yml
package.json

Just Setting the Baseline for V7 as an integration branch.

Increment Major Version

---

.github/workflows/deploy.yml
.github/workflows/node.js.yml
package.json

Just the JSON Path Plus Updates for V7

Upgrade JSON-Path-Plus

---

.github/workflows/deploy.yml
.github/workflows/node.js.yml
package.json

Release v7

---

package.json

Upgrade the Version Number to version 7.1.0
This includes the new ConditionResult type introduced in #390

Upgrade Version Number to deploy 7.1.0

---

package.json

New version 7.2.0
This will include changes to allow the resolved value of values to be present on the condition results.

Bump Version to 7.2.0

---

docs/engine.md

Change removeOperator to removeOperatorDecorator

Typo - change documentation to removeOperatorDecorator
