dist/condition.js, dist/engine.js, dist/rule.js, docs/engine.md, docs/rules.md, examples/fact-dependency.js, package.json, src/condition.js, src/engine.js, src/rule.js, test/condition.test.js, test/engine-fact.test.js, test/rule.test.js
Adds support for traversing an object returned from a fact.
@ctaity @slmmm - will this work for solving your use cases?
=> Fact paths

CHANGELOG.md, README.md, dist/rule.js, docs/almanac.md, docs/engine.md, docs/rules.md, examples/01-hello-world.js, examples/02-nested-boolean-logic.js, examples/03-dynamic-facts.js, examples/04-fact-dependency.js, examples/05-optimizing-runtime-with-fact-priorities.js, examples/06-custom-operators.js, examples/07-rule-chaining.js, src/rule.js, test/engine-event.test.js, test/rule.test.js
- adds rule event emissions for success and failure
- formalizes `rule priorities` + `rule events` + `almanac.setRuntimeFact` as the recommended method for rule chaining
- updates docs and examples accordingly
fixes #7  and #10
=> Rule chaining

CHANGELOG.md, dist/almanac.js, package.json, src/almanac.js, test/engine-fact.test.js
Reported in #17; when a cached fact value was retrieved by the engine, path was not being interpreted.  This affected conditions using `.path` in two circumstances: when a dynamic fact returning an object was used in multiple rules, and constant facts passed to `engine.run()`
=> fix almanac.factValue incorrectly interpretting path

docs/rules.md
Converted hastag to first later to small case to make it work.
=> Hastags not working properly. Fixed it.

.gitignore, docs/walkthrough.md
Fixed some errors in the walkthrough and added helper methods to make it actually run.
I believe this will make it easier for users to understand...
=> Fix walkthrough so anyone who follows it will be able to actually run it

src/condition.js, test/engine-event.test.js
Adding `factResult` and `result` to the JSON generated for `Condition`
The use case here is that I'd like to store the results of a run and know what the fact (specifically facts that are computed) was at the time and the result of each condition. 
This will allow us to audit decision in the future and know exactly what the decision looked like at the time.
Feedback is welcome!
=> Add factResults to condition json if available, increase auditability.

src/rule.js
Hi @CacheControl !
I've already make single PR to make IE8 friendly version of your awesome project.
Don't you mind if we'll use "for" loop instead of Array.forEach? That's very important for me as I can't use polyfills in my project.
Looking forward to your decision,
Best regards!
=> Make compatible with IE8

src/condition.js
`instanceof` does not always return true for an array even if `array.isArray()`
return true and `Object.prototype.toString()` returns `[Object Array]`
http://blog.niftysnippets.org/2010/09/say-what.html#instanceof
https://stackoverflow.com/questions/28779255/is-instanceof-array-better-than-isarray-in-javascript
Fixes #124
=> Use Array.isArray instead of instanceof

docs/engine.md, package.json, src/almanac.js, src/engine.js, src/rule.js
This is considered a breaking change because previously all conditions with undefined facts would resolve `false`. With this change, undefined facts resolve as `undefined`.  This means the engine results will change for any rule that would evaluate as truthy given an `undefined` fact value. e.g.
```
{
'fact': 'age',
'operator': 'notEqual',
'value': 10
}
```
Would previously evaluate as `false`. It will not evaluate as `true`, because `undefined != 10`.
=> Fix undefined fact memory

docs/engine.md, examples/01-hello-world.js, examples/02-nested-boolean-logic.js, examples/03-dynamic-facts.js, examples/07-rule-chaining.js, src/engine.js, test/engine-run.test.js
Resolves #152 and #81 
This is a breaking change that will require a major version update to the library.
With this change, `engine.run()` now, instead of returning just `events`, will return an object with both `events` and the `almanac`, which can then be accessed after engine execution.
=> Engine.run now returns almanac in addition to events

.npmignore, package-lock.json, package.json, types/index.d.ts, types/index.test-d.ts
While `@types/json-rules-engine` was just recently added to DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38613), the types defined in that library didn't seem to be 100% complete or entirely accurate from what I could see. This would be an alternative that could hopefully be more carefully maintained than something outside the repository.
=> Add types (and tests) for distribution with the module

README.md, examples/01-hello-world.js, examples/02-nested-boolean-logic.js, examples/03-dynamic-facts.js, examples/04-fact-dependency.js, examples/05-optimizing-runtime-with-fact-priorities.js, examples/06-custom-operators.js, examples/07-rule-chaining.js, examples/08-fact-comparison.js, examples/09-rule-results.js
Changed import { Engine } from 'json-rules-engine' to const Engine = require('json-rules-engine').Engine in readMe and examples because the latest version node throws error. This is in reference to closed issue (Can't Import Engine #78)
=> { Engine }

README.md, examples/.gitignore, examples/01-hello-world.js, examples/02-nested-boolean-logic.js, examples/03-dynamic-facts.js, examples/04-fact-dependency.js, examples/05-optimizing-runtime-with-fact-priorities.js, examples/06-custom-operators.js, examples/07-rule-chaining.js, examples/08-fact-comparison.js, examples/09-rule-results.js, examples/package-lock.json, examples/package.json
=> Update examples to use json-rule-engine require instead of dist folder

CHANGELOG.md, docs/almanac.md, docs/engine.md, docs/facts.md, docs/rules.md, docs/walkthrough.md, package.json, src/almanac.js, src/engine.js, test/engine-fact.test.js, types/index.d.ts
adds path resolver engine option. This allows path syntax other than the `json-path` default. It also replaces the current `selectn` built-in fallback with a long term supported solution via the `pathResolver` callback. Fixes #210 and #187.
=> Path resolver

types/index.d.ts
From previous PRs, the `type` definition was missing `failureEvents` which is available when accessing through JS https://github.com/CacheControl/json-rules-engine/pull/242
This ensures the compiler can access `failureEvents` as well.
=> Add failureEvents to types

docs/engine.md, src/engine.js, src/rule.js, test/engine.test.js
@CacheControl as we talked, I kept engine.rules as an array. 
with this PR we expect that each rule will have a unique key. the name of the field is customizable in the engine's constructor as you can pass "ruleKeyField" default is ('id').
when adding rule if I see there is no unique key at rule[engine.ruleKeyField] I generate a random string so you can still remove it by key if you want to.
also added updateRule() which is removing the rule and adding him again.
let me know if there is something more I need to do. 
My project needs this functionality as each user in my app can create/remove/update his rules which are stored in MongoDB i need to be able to remove or update them by id.
all unit tests passed and I added 2 more.
=> refactored remove rule and added updateRule

docs/rules.md, examples/02-nested-boolean-logic.js, src/condition.js, src/rule.js, test/condition.test.js, test/engine-not.test.js, test/engine-recusive-rules.test.js, test/rule.test.js, types/index.d.ts
I've had difficulty expressing certain rules in a readable way without the ability to negate conditions.
For instance if I wanted to create a rule saying "trigger an event when there is not any condition which is true," I would instead have to express this as "trigger an event when all conditions are false." This means that I would have to write each condition as its logical negation, which potentially affects the readability of the condition.
These changes add in a new `not` boolean operator alongside `all` and `any` which negates the result of whatever single condition is nested inside it.
I believe this addresses issue https://github.com/CacheControl/json-rules-engine/issues/269.
=> Add "not" boolean operator

docs/engine.md, docs/rules.md, examples/10-condition-sharing.js, examples/package.json, src/condition.js, src/engine.js, src/rule.js, test/engine-condition.test.js, test/rule.test.js, types/index.d.ts
This introduces the concept of Condition sharing which allows regular conditions that are given a well-known name and to be added to the engine. Rules can reference the condition by including a `condition` property on a condition.
example based on #296 
```js
engine.setCondition('isMinor', {
all: [
{
fact: 'age',
operator: 'lessThan',
value: { fact: 'drinkingAge' }
}
]
});
engine.addRule({
conditions: {
all: [
{ not: { condition: 'isMinor' } },
{
fact: 'currentTime',
operator: 'lessThanInclusive',
value: { fact: 'lastCall' }
}
]
},
event: {
type: 'AlcoholicBeverageSelection'
}
});
// condition references can be top-level conditions so it's possible for a rule to just be a condition reference.
engine.addRule({
conditions: {
condition: 'isMinor'
},
event: {
type: 'SoftDrinkSelection'
}
}) …
```
=> Condition Sharing

package.json, src/rule.js, test/engine-condition.test.js
There was no test for the top-level condition reference and this was failing because it was being treated as a `not`
Add a test and fix the bug.
=> Fix Top Level Condition Reference Failure

docs/engine.md, docs/rules.md, examples/11-using-facts-in-events.js, package.json, src/almanac.js, src/condition.js, src/engine.js, src/rule-result.js, src/rule.js, test/engine-event.test.js
This adds support via an engine option flag to allow event params to include reference to facts like values do.
The structure of this is that for event parameters the top-level keys may have the value: `{ "fact": "<fact id>" }` at which point they'll be converted into the actual fact value when the rule is evaluated. You can use path and param helpers the same as any other reference to a fact.
The primary use case for this is as a way to externaize values for the events into facts so they can be shared, or so they can change without the rule needing to change. Additionally moving away from needing event / rule specific handlers allows the rules to more completely configure the system for instance:
```js
const maxBidRule = {
conditions: {
all: [
{ condition: "desireable" },
{
fact: …
```
=> Support Facts In Events

package.json, src/rule-result.js
We didn't have lodash as a dependency instead having lodash.isObject builds were working because lodash was a dev dependency.
Resolves #346
=> Fix usage of lodash

docs/almanac.md, docs/engine.md, examples/07-rule-chaining.js, examples/12-using-custom-almanac.js, src/almanac.js, src/engine.js, src/json-rules-engine.js, test/almanac.test.js, test/condition.test.js, test/engine-run.test.js, types/index.d.ts
This is a generic suggestion to resolve #314
Rather than having the Almanac class be completely hidden except in event properties we move to having the Almanac be an option that can be passed into the run call. This allows for extensions of Almanacs that can do things that the standard Almanac can't do.
In order to support this properly a new addFact method was added to the Almanac that replaces the addRuntimeFact method but also allows dynamic facts to be added.
=> Custom almanac

types/index.d.ts, types/index.test-d.ts
When directly subscribing to an emitted event through the engine's `on` method, the parameter types for the callback function do not match the types of the parameters at runtime. This leads to compilation errors when directly subscribing to events.
```ts
// subscribe directly to the 'young-adult' event
engine.on('young-adult-rocky-mnts', (params) => {
// params: {
//   giftCard: 'amazon',
//   value: 50
// }
// Should work!
engine.on('young-adult-rocky-mnts', ({ giftCard, value }) => { // Property 'value' does not exist on type 'Event'.
console.log(`I got an ${giftCard} card with $${value}!`) 
})
});
```
```
index.ts:60:40 - error TS2339: Property 'giftCard' does not exist on type 'Event'.
60 engine.on('young-adult-rocky-mnts', ({ giftCard, value }) => { // Property 'value' does not exist …
```
=> fix: Updated engine on overload to include generic option

docs/engine.md, docs/rules.md, examples/13-using-operator-decorators.js, examples/package-lock.json, src/engine-default-operator-decorators.js, src/engine.js, src/json-rules-engine.js, src/operator-decorator.js, src/operator-map.js, test/engine-operator-map.test.js, test/engine.test.js, test/operator-decorator.test.js, types/index.d.ts, types/index.test-d.ts
Operator Decorators are a new feature for the JSON rules engine. This resolves a number of issues including #374 
**How do they work?**
A decorator, or decorators are declared in the operator name using the colon ":" character to separate it from the main operator. For instance "everyFact:lessThan" would decorate the lessThan operator with the everyFact decorator.
**What Decorators are Included** 
By default the following decorators are included
* `someFact/someValue` - uses `Array.some` to determine if some of the facts or some of the values match the decorated operator.
* `everyFact/everyValue` - uses `Array.every` to determine if all of the facts or all of the values match the decorated operator.
* `not` - applies a boolean not to the result of the decorated operator
* `swap` - swaps …
=> Operator decorators

package.json, src/almanac.js, src/rule-result.js
The presence of the dependency "lodash.isobjectlike": "^4.0.0" in the code is causing BlackDuck to report a vulnerability issue related to Prototype Pollution. 
However, it seems unnecessary to load this dependency separately because the function isObjectLike is already available in the "lodash" library. 
Furthermore, the issue related to Prototype Pollution has been addressed and fixed in version 4.17.12 of "lodash". 
You can refer to the following link for additional information: https://security.snyk.io/vuln/SNYK-JS-LODASH-608086
=> Remove lodash.isobjectlike package

test/engine-event.test.js, types/index.d.ts, types/index.test-d.ts
This PR closes #352 by improving the typing of [RuleResult](https://github.com/CacheControl/json-rules-engine/blob/ae8fa0553968ce3ac2dd5dfa9508ce208a852047/types/index.d.ts#L156).
=> fix: improve typing of RuleResult

test/engine-event.test.mjs, test/types.test-d.mts, types/index.d.ts
This re-applies the changes from #390 onto v8.
=> re-apply the changes from #390 onto v8

src/condition.js, src/rule.js, test/acceptance/acceptance.js, test/engine-event.test.js, test/engine-fact-comparison.test.js, types/index.d.ts
Hello!
I noticed the issue mentioned in #310, which is important for my use case, so I tried to address it with this pull request.
My implementation approach is straightforward. When setting the factResult for a condition, if the value property is an object, I include the rightSideValue as the factResult.
I'm eager to see this merged, as it is of great interest to me.
=> Add RightSideComparisonResult as factResult

package.json
This pull request updates the jsonpath-plus dependency to version 10.2.0 to address a critical Remote Code Execution (RCE) vulnerability (CVE-2024-21534) [Affecting jsonpath-plus package, versions <10.2.0](https://security.snyk.io/vuln/SNYK-JS-JSONPATHPLUS-7945884). The vulnerability stems from improper input sanitization in earlier versions, allowing attackers to execute arbitrary code by exploiting the unsafe default use of the Node.js vm module.
Changes:
- Upgraded jsonpath-plus to version 10.2.0 in package.json to leverage the latest security patches and improvements.
- Ran dependency audits and verified compatibility with existing functionality.
Benefits:
- Fixes a critical security issue (CVSS 9.8), reducing the risk of exploitation.
- Ensures safer handling of JSONPath queries …
=> Upgrade JSON-Path-Plus to V10.2.0.

src/rule.js, test/rule.test.js, types/index.d.ts
Currently, the [types](https://github.com/CacheControl/json-rules-engine/blob/00061aceb905d1b0e8f571ef3baf200dc32ded61/types/index.d.ts#L178) suggest that `Rule` has a property called `event`, but the property is actually called `ruleEvent`, as evidenced by [this test](https://github.com/CacheControl/json-rules-engine/blob/00061aceb905d1b0e8f571ef3baf200dc32ded61/test/rule.test.js#L32). This PR fixes that by changing the type of `Rule`. This is not breaking because any TypeScript code referring to a `Rule`'s `event` can never have worked.
=> call Rule.ruleEvent by its correct name

package.json
This pull request updates the jsonpath-plus dependency to version 10.3.0 to address a critical Remote Code Execution (RCE) vulnerability (https://github.com/advisories/GHSA-pppg-cpfq-h7wr) [Affecting jsonpath-plus package, versions <10.2.0](https://security.snyk.io/vuln/SNYK-JS-JSONPATHPLUS-8719585). The vulnerability stems from improper input sanitization in earlier versions, allowing attackers to execute arbitrary code by exploiting the unsafe default use of the Node.js vm module.
Changes:
Upgraded jsonpath-plus to version 10.3.0 in package.json to leverage the latest security patches and improvements.
Ran dependency audits and verified compatibility with existing functionality.
Benefits:
Fixes a critical security issue (CVSS 9.3), reducing the risk of exploitation.
Ensures safer …
=> Upgrade JSON-Path-Plus to V10.3.0
